spring.application.name=dubbo-provider
spring.main.allow-bean-definition-overriding=true
server.port=8080
dubbo.registry.address=nacos://192.168.228.100:8848
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
dubbo.protocol.serialization=kryo
dubbo.provider.loadbalance=roundrobin
endpoints.dubbo.enabled=true
management.health.dubbo.status.defaults=memory
management.health.dubbo.status.extras=threadpool
management.endpoints.web.exposure.include=*